# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: 定时发送下班提醒

on:
#  push:
#    branches: [ "master" ]
#  pull_request:
#    branches: [ "master" ]
  schedule:
    # * is a special character in YAML so you have to quote this string
    # * utc时间据我们慢8个小时 https://crontab.guru/
    - cron:  '40 10 * * 1-5'
permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: 设置执行环境的时区
      uses: szenius/set-timezone@v1.0
      with:
          timezoneLinux: "Asia/Shanghai"
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        cache: 'pip' # caching pip dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: run
      run: python dd/xbApi.py
    env:
      DD_ACCESS_TOKEN: ${{ secrets.DD_ACCESS_TOKEN }}
      DD_SIGN_SECRET: ${{ secrets.DD_SIGN_SECRET }}
